const items=[
{id:1,title:'Cognac Leather Lounge Chair',category:'Seating',price:285,bids:14,time:'2h 18m',seller:'Mia R.',tag:'Ending soon',img:'https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=800&q=85'},
{id:2,title:'Vintage Oak Dining Table',category:'Tables',price:460,bids:8,time:'5h 42m',seller:'Daniel K.',tag:'Local favorite',img:'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=85'},
{id:3,title:'Woven Cane Sideboard',category:'Storage',price:190,bids:5,time:'1d 3h',seller:'Sofia M.',tag:'Just listed',img:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&q=85'},
{id:4,title:'Italian Marble Lamp',category:'Lighting',price:95,bids:11,time:'3h 09m',seller:'Jonah B.',tag:'Ending soon',img:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=85'},
{id:5,title:'Handwoven Wool Rug',category:'Decor',price:150,bids:7,time:'8h 26m',seller:'Leah C.',tag:'Popular',img:'https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=800&q=85'},
{id:6,title:'Bentwood Reading Chair',category:'Seating',price:120,bids:3,time:'1d 8h',seller:'Eli V.',tag:'Just listed',img:'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=800&q=85'},
{id:7,title:'Brass Nesting Tables',category:'Tables',price:175,bids:9,time:'6h 10m',seller:'Nora L.',tag:'Local favorite',img:'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=800&q=85'},
{id:8,title:'Mid-Century Credenza',category:'Storage',price:370,bids:18,time:'4h 51m',seller:'Rory A.',tag:'Ending soon',img:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=85'}];
let current=items[0],bid=290;const grid=document.querySelector('#grid');
function render(filter='All'){grid.innerHTML=items.filter(x=>filter==='All'||x.category===filter).map(x=>'<article class="card" data-id="'+x.id+'"><div class="photo"><img src="'+x.img+'" alt="'+x.title+'"><span class="pill">'+x.tag+'</span><button class="heart">♡</button></div><div class="info"><h3>'+x.title+'</h3><div><span>Current bid <strong>$'+x.price+'</strong></span><span class="time">'+x.time+'</span></div><p>'+x.bids+' bids · '+x.category+'</p></div></article>').join('');document.querySelectorAll('.card').forEach(el=>el.onclick=e=>{if(e.target.closest('.heart')){e.target.textContent=e.target.textContent==='♡'?'♥':'♡';return}current=items.find(x=>x.id==el.dataset.id);showListing()})}
function showListing(){bid=current.price+5;['Image','Title','Category','Seller','Price','Bids','Time'].forEach(k=>{let el=document.querySelector('#modal'+k);if(el)el[k==='Image'?'src':'textContent']=k==='Image'?current.img:k==='Title'?current.title:k==='Category'?current.category:k==='Seller'?current.seller:k==='Price'?'$'+current.price:k==='Bids'?current.bids+' bids':current.time});document.querySelector('#yourBid').textContent='$'+bid;document.querySelector('#listingOverlay').classList.add('open')}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>document.querySelector('#authOverlay').classList.add('open'));document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('.overlay').classList.remove('open'));document.querySelectorAll('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)o.classList.remove('open')});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});document.querySelectorAll('[data-category]').forEach(x=>x.onclick=()=>render(x.dataset.category));
document.querySelector('#plus').onclick=()=>{bid+=5;document.querySelector('#yourBid').textContent='$'+bid};document.querySelector('#minus').onclick=()=>{if(bid>current.price+5){bid-=5;document.querySelector('#yourBid').textContent='$'+bid}};document.querySelector('#placeBid').onclick=()=>{current.price=bid;current.bids++;document.querySelector('#listingOverlay').classList.remove('open');render();let t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)};
function dashboard(){document.querySelector('main').style.display='none';document.querySelector('footer').style.display='none';document.querySelector('header').style.display='none';document.querySelector('#dashboard').classList.add('show');document.querySelector('#dashList').innerHTML=items.slice(0,4).map(x=>'<article class="dashitem"><img src="'+x.img+'" alt=""><div><h3>'+x.title+'</h3><p>'+x.bids+' bids · Pickup in Tampa</p></div><div><span>Current bid</span><b>$'+x.price+'</b></div><div class="ending">Ends in '+x.time+'</div></article>').join('')}
document.querySelector('#sellButton').onclick=dashboard;document.querySelector('#sellButton2').onclick=dashboard;document.querySelector('#back').onclick=()=>{document.querySelector('main').style.display='block';document.querySelector('footer').style.display='block';document.querySelector('header').style.display='flex';document.querySelector('#dashboard').classList.remove('show');scrollTo(0,0)};document.querySelector('#create').onclick=()=>document.querySelector('#authOverlay').classList.add('open');render();
